name: Execute all tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 12,16 * * *'

env: 
  GITHUB_TOKEN: INDOCOMTUDONODESAFIODINHEIROW

jobs: 
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1
    
      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build --if-present
    
      - name: Exec integration tests
        run: npm test
