name: Execute all tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 12,16 * * *'
  
jobs: 
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2

    steps:
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
    
    steps:
      - name: Install dependencies
        run: npm install
    
    steps:
      - name: Exec integration tests
        run: npm test
